name = "go-tracker-reminder"
main = "index.js"
compatibility_date = "2023-09-04"

# Set up hourly cron trigger
[triggers]
crons = ["0 * * * *"] # Runs at the top of every hour

# Enable logging
[observability.logs]
enabled = true 